name: "Tests: E2E"
on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  e2erun:  
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: yarn test 
