name: "Tests: E2E"
on:
  workflow_dispatch:
     inputs:
      notify:
        description: Post the results to webex
        required: true
        default: true
        type: boolean
      retry:
        description: Rerun required for failed test cases in the first try
        required: true
        default: true
        type: boolean
      environment:
        description: Test Application Environment
        required: true
        default: ci
        type: string
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  e2erun:  
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.36.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Test Script
        uses: actions/github-script@v6
        with:
          script: |
            const retry = ${{inputs.retry}}
            console.log(`Rettry=${retry}`)
      - name: Run tests
        shell: bash
        run: |
          command=("test")
          retry=${{inputs.retry}}
          if [ "$retry" = true ] ; then
            command+=("--retries=2")
          fi
          echo $retry
          echo "${command[@]}"
          HOME=/root yarn "${command[@]}"
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "playwright-report/xunit.xml"
        if: always()
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            playwright-report/**/*
            artifacts/**/**
      - name: Post Notification
        run: |
          message="#### This is a test message"
          totalCount=5
          failCount=1
          skipCount=0
          passCount=4
          WORKFLOW_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo $WORKFLOW_URL
          msg="<h2>PIAM E2E Regression - Cross Browser Tests </h2><hr><b>Test Status : &#10060; FAILED </b><br/> \
          <b><a href=http://144.254.67.217:3000/d/05jLPAy4k/piam-e2e-integration-tests?orgId=1&var-RunID'${BRANCH_NAME}'/'${BUILD_NUMBER}'&from=now-7d&to=now>Grafana Dashboard</a></b><br/> \
          <b><a href='$WORKFLOW_URL'>Workflow Run</a></b> \
          <pre>| <b>Test Summary</b>  |  Total : ${totalCount}  |  Failures: ${failCount}  |  Skipped: ${skipCount}  | Passed: ${passCount}  |</pre>"
          echo "$msg"
          # curl -X POST --data-raw "{\"markdown\": \"$message\"}" -H "Content-Type:application/json" \
          # https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNTIyMmE3NDEtNTI0Zi00ODM0LWJmMWMtYjg5NTQzMWE1NTNi
